version: '3'


services:
  nodejs:
    build: .
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - "./:/usr/src/app"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=KJNnkN
      - MONGODB_ADMIN_PASS=ikjmnl97
      - MONGO_INITDB_DATABASE=commerce
      - MONGO_INITDB_ROOT_USERNAME=pknllnjNKJN
      - MONGO_INITDB_ROOT_PASSWORD=LJNkhBLJHV
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    networks:
      - app-network
    ports:
      - "27018:27017"

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email kostyalopatkin777@gmail.com --agree-tos --no-eff-email --staging -d kovilook.com.ua  -d www.kovilook.com.ua

volumes:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/e-commerce/dhparam/
      o: bind
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
#      device: /home/dima/Documents/projects/magi/e-commerce-shop/e-commerce-shop-back/
      device: /home/e-commerce/
      o: bind
  mongo-data:
    driver: local
    driver_opts:
      type: none
#      device: /home/dima/Documents/projects/magi/e-commerce-shop/e-commerce-shop-back/mongo/
       device: /home/e-commerce/
      o: bind
networks:
  app-network:
    driver: bridge
