version: "2"
services:
  app:
    container_name: app
    volumes:
      - "./:/usr/src/app"
    build: .
    ports:
      - "7000:7000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./docker/mongodata:/var/lib/mongo
    ports:
      - "27018:27017"
